[build]
builder = "nixpacks"
buildCommand = "npm install && cd shared && npm install && npx tsc && cd ../server && npm install && npx tsc"
root = "/"

[deploy]
startCommand = "cd server && node dist/index.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
